<?php

$lessons = [
    'LCLNX' => 'N',
    'LCLXN' => 'N',
    'LLNX' => 'N',
    'LLXN' => 'N',
    'LNCX' => 'N',
    'LXNN' => 'L',
    'NCNLCX' => 'L',
    'NCNLX' => 'L',
    'NCNXCL' => 'L',
    'NCNXL' => 'L',
    'NCXLCL' => 'N',
    'NCXLL' => 'N',
    'NLX' => 'L',
    'NNLCX' => 'L',
    'NNLX' => 'L',
    'NNX' => 'L',
    'NNXCL' => 'L',
    'NNXL' => 'L',
    'NXLCL' => 'N',
    'NXLL' => 'N',
    'XCNLCL' => 'N',
    'XCNLL' => 'N',
    'XLL' => 'N',
    'XLNN' => 'L',
    'XNL' => 'N',
    'XNLCL' => 'N',
    'XNLL' => 'N',
];
