<?php

declare(strict_types=1);

namespace micros\splitname\Database\migrations;

use Micros\Splitname\Models\Lesson;
use Micros\Splitname\Models\SplitLesson;
use Micros\Splitname\Models\SplitRule;
use Micros\Splitname\Models\SplitSustitution;
use Micros\Splitname\Models\SplitTerm;
use Micros\Splitname\PartCleaner;

class Load
{
    private $partCleaner;
    public function __construct()
    {
        $this->partCleaner = new PartCleaner();
    }

    public function loadTerms()
    {

        // Male names
        $terms['M'] = [
            'abel',
            'adolfo',
            'adrián',
            'agustin',
            'albeiro',
            'alberto',
            'alejandro',
            'álex',
            'alexander',
            'alexis',
            'alfonso',
            'alfredo',
            'alirio',
            'alonso',
            'álvaro',
            'anderson',
            'andres',
            'ángel',
            'anibal',
            'antonio',
            'arbey',
            'ariel',
            'arley',
            'armando',
            'arnulfo',
            'arturo',
            'augusto',
            'bayron',
            'bernardo',
            'brayan',
            'bryan',
            'camilo',
            'carlos',
            'cesar',
            'christian',
            'cristhian',
            'cristian',
            'dairo',
            'daniel',
            'danilo',
            'danny',
            'dario',
            'david',
            'didier',
            'diego',
            'domingo',
            'duvan',
            'dylan',
            'edgar',
            'edinson',
            'edison',
            'edisson',
            'eduard',
            'eduardo',
            'edwar',
            'edward',
            'edwin',
            'efrain',
            'efren',
            'elias',
            'eliecer',
            'elkin',
            'emilio',
            'emiro',
            'enrique',
            'erick',
            'ernesto',
            'esteban',
            'evelio',
            'faber',
            'fabian',
            'fabio',
            'farley',
            'federico',
            'felipe',
            'felix',
            'fernando',
            'ferney',
            'francisco',
            'frank',
            'freddy',
            'fredy',
            'gabriel',
            'gerardo',
            'germán',
            'gerson',
            'gilberto',
            'giovanni',
            'giovanny',
            'giovany',
            'gonzalo',
            'gregorio',
            'guillermo',
            'gustavo',
            'harold',
            'harvey',
            'hector',
            'henry',
            'heriberto',
            'hernan',
            'hernando',
            'herney',
            'hoover',
            'horacio',
            'hugo',
            'humberto',
            'ignacio',
            'isaac',
            'ismael',
            'iván',
            'jaime',
            'jair',
            'jairo',
            'james',
            'javier',
            'jean',
            'jeferson',
            'jefferson',
            'jeison',
            'jeisson',
            'jesús',
            'jhan',
            'jhoan',
            'jhon',
            'jhonatan',
            'jhonny',
            'jimmy',
            'joan',
            'joaquin',
            'johan',
            'john',
            'johnny',
            'jonatan',
            'jonathan',
            'jordan',
            'jorge',
            'josé',
            'josue',
            'juan',
            'julián',
            'julio',
            'kevin',
            'leandro',
            'leo',
            'león',
            'leonardo',
            'libardo',
            'lucas',
            'luis',
            'manuel',
            'marcelo',
            'marco',
            'marcos',
            'marino',
            'mario',
            'marlon',
            'martín',
            'mateo',
            'mauricio',
            'michael',
            'miguel',
            'miller',
            'milton',
            'nel',
            'nelson',
            'nestor',
            'nicolás',
            'omar',
            'orlando',
            'oscar',
            'oswaldo',
            'ovidio',
            'pablo',
            'paul',
            'paulo',
            'pedro',
            'rafael',
            'ramiro',
            'ramon',
            'raul',
            'rene',
            'ricardo',
            'ricaurte',
            'richard',
            'roberto',
            'rodolfo',
            'rodrigo',
            'roger',
            'rolando',
            'román',
            'ronald',
            'ruben',
            'samir',
            'santiago',
            'santos',
            'saul',
            'sebastian',
            'segundo',
            'sergio',
            'sigifredo',
            'steven',
            'stevens',
            'stiven',
            'uriel',
            'vicente',
            'victor',
            'virgilio',
            'walter',
            'william',
            'wilmar',
            'wilmer',
            'wilson',
            'xavier',
            'yeison',
            'yesid',
        ];

        // Female names
        $terms['F'] = [
            'abril',
            'adriana',
            'agustina',
            'aida',
            'alba',
            'alejandra',
            'alexandra',
            'alicia',
            'alix',
            'amalia',
            'amanda',
            'amelia',
            'amparo',
            'ana',
            'andrea',
            'angela',
            'ángeles',
            'angelica',
            'angie',
            'angye',
            'anyela',
            'anyi',
            'astrid',
            'aura',
            'aurora',
            'beatriz',
            'betty',
            'bibiana',
            'blanca',
            'brigitte',
            'camila',
            'carla',
            'carmen',
            'carmenza',
            'carol',
            'carolina',
            'catalina',
            'catherine',
            'cecilia',
            'cindy',
            'clara',
            'claudia',
            'clemencia',
            'concepción',
            'constanza',
            'consuelo',
            'cristina',
            'cruz',
            'dahiana',
            'daissy',
            'daniela',
            'danna',
            'dary',
            'dayana',
            'dayanna',
            'deisy',
            'deysi',
            'diana',
            'diva',
            'dora',
            'doris',
            'edith',
            'edna',
            'elena',
            'eliana',
            'elizabeth',
            'elsa',
            'elvira',
            'ema',
            'emilce',
            'emilia',
            'emma',
            'erica',
            'erika',
            'esperanza',
            'estefania',
            'esther',
            'eugenia',
            'evelyn',
            'fabiola',
            'fanny',
            'fernanda',
            'flor',
            'francisca',
            'francy',
            'gabriela',
            'genny',
            'geraldine',
            'gilma',
            'gina',
            'gineth',
            'ginna',
            'giovana',
            'giovanna',
            'gisela',
            'giselle',
            'gladys',
            'gloria',
            'graciela',
            'guadalupe',
            'heidy',
            'helena',
            'ibeth',
            'ines',
            'ingrid',
            'irene',
            'iris',
            'isabel',
            'ivonne',
            'janeth',
            'janneth',
            'jazmin',
            'jeimmy',
            'jeniffer',
            'jennifer',
            'jenniffer',
            'jenny',
            'jesica',
            'jessica',
            'jhoanna',
            'jimena',
            'jineth',
            'johana',
            'johanna',
            'josefina',
            'juana',
            'judith',
            'judy',
            'julia',
            'juliana',
            'julie',
            'juliet',
            'julieth',
            'july',
            'karen',
            'karime',
            'karina',
            'karol',
            'katerine',
            'katherin',
            'katherine',
            'katherinne',
            'katia',
            'kelly',
            'lady',
            'laura',
            'leidy',
            'lenis',
            'leonor',
            'leticia',
            'leydi',
            'leydy',
            'libia',
            'liceth',
            'lida',
            'lidia',
            'ligia',
            'lilian',
            'liliana',
            'lina',
            'linda',
            'lisbet',
            'lisbeth',
            'liset',
            'liseth',
            'lisette',
            'lisseth',
            'liz',
            'liza',
            'lizbeth',
            'lizeth',
            'lorena',
            'lucero',
            'lucía',
            'lucrecia',
            'lucy',
            'ludy',
            'luisa',
            'luz',
            'mabel',
            'magda',
            'magdalena',
            'magnolia',
            'maira',
            'manuela',
            'mar',
            'marcela',
            'marcia',
            'margarita',
            'maría',
            'mariana',
            'marina',
            'maritza',
            'marly',
            'marlyn',
            'marta',
            'martha',
            'martina',
            'mary',
            'mayerli',
            'mayerly',
            'mayra',
            'melba',
            'melisa',
            'melissa',
            'mercedes',
            'mery',
            'milena',
            'mireya',
            'miriam',
            'monica',
            'muriel',
            'myriam',
            'nancy',
            'natalia',
            'nataly',
            'nathalia',
            'nelly',
            'nelsy',
            'nidia',
            'nini',
            'noa',
            'nohora',
            'nora',
            'norma',
            'nubia',
            'nury',
            'nydia',
            'ofelia',
            'olga',
            'omaira',
            'pamela',
            'paola',
            'patricia',
            'paula',
            'paulina',
            'piedad',
            'pilar',
            'raquel',
            'rocio',
            'rosa',
            'rosario',
            'ruby',
            'ruth',
            'sandra',
            'sara',
            'shirley',
            'silvia',
            'sindy',
            'sirley',
            'socorro',
            'sofía',
            'sol',
            'sonia',
            'sorley',
            'stefanny',
            'stefany',
            'stella',
            'stephanie',
            'stephany',
            'sulay',
            'susana',
            'tania',
            'tatiana',
            'teresa',
            'trinidad',
            'valentina',
            'valeria',
            'vanesa',
            'vanessa',
            'verónica',
            'victoria',
            'vilma',
            'virginia',
            'vivian',
            'viviana',
            'wendy',
            'ximena',
            'xiomara',
            'yadira',
            'yamile',
            'yaneth',
            'yasmin',
            'yazmin',
            'yeimy',
            'yeiny',
            'yenny',
            'yeny',
            'yesenia',
            'yesica',
            'yina',
            'yineth',
            'yohana',
            'yohanna',
            'yolanda',
            'yolima',
            'yudy',
            'yuli',
            'yuliana',
            'yulieth',
            'yuly',
            'yurani',
            'yurany',
            'yuri',
            'yurley',
            'yury',
            'zulma',
            'zuly',
        ];
        // Surnames
        $terms['L'] = [
            'abad',
            'abella',
            'abril',
            'acero',
            'acevedo',
            'achury',
            'acosta',
            'acuña',
            'afanador',
            'agredo',
            'agudelo',
            'aguilar',
            'aguilera',
            'aguirre',
            'ahumada',
            'alarcon',
            'alba',
            'albarracin',
            'aldana',
            'alegria',
            'aleman',
            'alfonso',
            'almeida',
            'alonso',
            'alvarado',
            'álvarez',
            'alvear',
            'alzate',
            'amado',
            'amaya',
            'amezquita',
            'amortegui',
            'anaya',
            'andrade',
            'angarita',
            'angel',
            'angulo',
            'ante',
            'antolinez',
            'anzola',
            'aparicio',
            'aponte',
            'aponza',
            'aragon',
            'arana',
            'aranda',
            'arango',
            'araque',
            'araujo',
            'arbelaez',
            'arboleda',
            'arce',
            'archila',
            'arcila',
            'arciniegas',
            'arcos',
            'ardila',
            'arenas',
            'arevalo',
            'arguello',
            'arias',
            'aricapa',
            'arismendi',
            'aristizabal',
            'ariza',
            'arredondo',
            'arrieta',
            'arroyave',
            'arroyo',
            'arteaga',
            'artunduaga',
            'astudillo',
            'atehortua',
            'avella',
            'avellaneda',
            'avendaño',
            'avila',
            'ayala',
            'badillo',
            'baena',
            'baez',
            'bahamon',
            'balaguera',
            'balanta',
            'balcazar',
            'ballen',
            'ballesteros',
            'banguero',
            'bañol',
            'baquero',
            'baracaldo',
            'barahona',
            'barajas',
            'barbosa',
            'baron',
            'barragan',
            'barrera',
            'barrero',
            'barreto',
            'barriga',
            'barrios',
            'barros',
            'bastidas',
            'basto',
            'bautista',
            'bayona',
            'becerra',
            'bedoya',
            'bejarano',
            'beleño',
            'bello',
            'beltran',
            'benavides',
            'benitez',
            'berdugo',
            'bermudez',
            'bernal',
            'berrio',
            'bertel',
            'betancourt',
            'betancourth',
            'betancur',
            'blanco',
            'blandon',
            'bobadilla',
            'bocanegra',
            'bohorquez',
            'bolaños',
            'bolívar',
            'bonilla',
            'borja',
            'botello',
            'botero',
            'bravo',
            'briceño',
            'briñez',
            'bueno',
            'buitrago',
            'bulla',
            'burbano',
            'burgos',
            'bustamante',
            'bustos',
            'cabal',
            'caballero',
            'cabezas',
            'cabra',
            'cabrera',
            'caceres',
            'cadavid',
            'cadena',
            'caicedo',
            'cala',
            'calderon',
            'calixto',
            'calle',
            'calvo',
            'camacho',
            'camargo',
            'camelo',
            'campo',
            'campos',
            'cañas',
            'cano',
            'cañon',
            'cantillo',
            'cantor',
            'carabali',
            'caraballo',
            'cardenas',
            'cardona',
            'cardozo',
            'carmona',
            'caro',
            'carranza',
            'carrascal',
            'carrasco',
            'carreño',
            'carrero',
            'carrillo',
            'carrizosa',
            'carvajal',
            'casallas',
            'casas',
            'castañeda',
            'castaño',
            'castelblanco',
            'castellanos',
            'castiblanco',
            'castillo',
            'castrillon',
            'castro',
            'ceballos',
            'cediel',
            'celis',
            'cely',
            'cepeda',
            'ceron',
            'cervantes',
            'cespedes',
            'cetina',
            'chacon',
            'chamorro',
            'chaparro',
            'charry',
            'chavarro',
            'chaverra',
            'chaves',
            'chavez',
            'chia',
            'chica',
            'cifuentes',
            'cipagauta',
            'clavijo',
            'cobo',
            'cobos',
            'colmenares',
            'colorado',
            'conde',
            'contreras',
            'coral',
            'cordero',
            'cordoba',
            'coronado',
            'corrales',
            'correa',
            'corredor',
            'cortes',
            'corzo',
            'cote',
            'coy',
            'cristancho',
            'cruz',
            'cuadrado',
            'cuadro',
            'cuartas',
            'cubides',
            'cubillos',
            'cucaita',
            'cuellar',
            'cuenca',
            'cuero',
            'cuervo',
            'cuevas',
            'cuta',
            'davila',
            'daza',
            'delgadillo',
            'delgado',
            'devia',
            'díaz',
            'diez',
            'dominguez',
            'dorado',
            'doria',
            'duarte',
            'dueñas',
            'duque',
            'durán',
            'durango',
            'dvries',
            'echeverri',
            'echeverry',
            'elvira',
            'enciso',
            'enriquez',
            'eraso',
            'erazo',
            'escalante',
            'escamilla',
            'escarria',
            'escobar',
            'escorcia',
            'eslava',
            'españa',
            'espejo',
            'espinal',
            'espinel',
            'espinosa',
            'espitia',
            'esquivel',
            'esteban',
            'estevez',
            'estrada',
            'estupiñan',
            'fajardo',
            'fandiño',
            'farfan',
            'fernández',
            'ferreira',
            'fierro',
            'figueredo',
            'figueroa',
            'flechas',
            'florez',
            'florian',
            'fonseca',
            'fontalvo',
            'forero',
            'forigua',
            'franco',
            'fuentes',
            'gaitan',
            'galan',
            'galarza',
            'galeano',
            'galindo',
            'gallego',
            'gallo',
            'galvez',
            'galvis',
            'gamarra',
            'gamba',
            'gamboa',
            'garavito',
            'garay',
            'garces',
            'garcía',
            'garnica',
            'garzon',
            'gaviria',
            'gelves',
            'gelvez',
            'gil',
            'giraldo',
            'giron',
            'godoy',
            'gómez',
            'gonzález',
            'gordillo',
            'graciano',
            'grajales',
            'granada',
            'granados',
            'granobles',
            'grimaldos',
            'grisales',
            'gualdron',
            'guapacha',
            'guaqueta',
            'guarin',
            'güemes',
            'guerra',
            'guerrero',
            'guevara',
            'guio',
            'gutiérrez',
            'guzman',
            'henao',
            'hernández',
            'herrera',
            'hidalgo',
            'higuera',
            'higuita',
            'hincapie',
            'holguin',
            'hoyos',
            'huertas',
            'humanez',
            'hurtado',
            'ibáñez',
            'ibarguen',
            'ibarra',
            'idarraga',
            'idrobo',
            'iglesias',
            'infante',
            'isaza',
            'izquierdo',
            'jacome',
            'jaimes',
            'jara',
            'jaramillo',
            'jauregui',
            'jerez',
            'jiménez',
            'jojoa',
            'joya',
            'julio',
            'jurado',
            'ladino',
            'lagos',
            'lancheros',
            'lara',
            'largo',
            'larrahondo',
            'larrotta',
            'lasso',
            'latorre',
            'laverde',
            'leal',
            'leguizamon',
            'lemus',
            'lenis',
            'león',
            'lievano',
            'lizarazo',
            'lizcano',
            'llano',
            'llanos',
            'llorente',
            'loaiza',
            'lobo',
            'loboa',
            'loboguerrero',
            'londoño',
            'lopera',
            'lópez',
            'lozada',
            'lozano',
            'lucero',
            'lugo',
            'luna',
            'macea',
            'machado',
            'macias',
            'madrid',
            'madrigal',
            'mafla',
            'mahecha',
            'malagon',
            'malaver',
            'maldonado',
            'mancilla',
            'mancipe',
            'manrique',
            'mantilla',
            'marin',
            'mariño',
            'marles',
            'marmolejo',
            'marquez',
            'marroquin',
            'martín',
            'martínez',
            'marulanda',
            'mateus',
            'matiz',
            'maturana',
            'maya',
            'mayor',
            'mayorga',
            'mazo',
            'medina',
            'mejia',
            'melendez',
            'melo',
            'mena',
            'mendez',
            'mendieta',
            'mendivelso',
            'mendoza',
            'meneses',
            'mera',
            'mercado',
            'merchan',
            'mesa',
            'meza',
            'millan',
            'mina',
            'miranda',
            'mogollon',
            'mojica',
            'molano',
            'molina',
            'moncada',
            'monroy',
            'monsalve',
            'montaña',
            'montañez',
            'montaño',
            'montealegre',
            'montenegro',
            'montero',
            'montes',
            'montiel',
            'montilla',
            'montoya',
            'mora',
            'morales',
            'moreno',
            'morera',
            'moscoso',
            'mosquera',
            'motta',
            'moya',
            'moyano',
            'munera',
            'munévar',
            'muñoz',
            'murcia',
            'muriel',
            'murillo',
            'najar',
            'ñañez',
            'naranjo',
            'narvaez',
            'navarrete',
            'navarro',
            'navas',
            'navia',
            'negrete',
            'neira',
            'nieto',
            'nieves',
            'niño',
            'noguera',
            'noreña',
            'noriega',
            'nova',
            'novoa',
            'nuñez',
            'obando',
            'ocampo',
            'ochoa',
            'ojeda',
            'olarte',
            'olave',
            'olaya',
            'olivares',
            'oliveros',
            'olmos',
            'oñate',
            'ordóñez',
            'orduz',
            'orejuela',
            'orjuela',
            'orozco',
            'orrego',
            'ortega',
            'ortegon',
            'ortíz',
            'osorio',
            'osorno',
            'ospina',
            'ospino',
            'ossa',
            'otálora',
            'otalvaro',
            'otero',
            'ovalle',
            'oviedo',
            'pabon',
            'pacheco',
            'pachon',
            'padilla',
            'paez',
            'palacio',
            'palacios',
            'palencia',
            'pallares',
            'palma',
            'palomino',
            'paniagua',
            'pantoja',
            'parada',
            'pardo',
            'paredes',
            'parra',
            'parrado',
            'pastrana',
            'patarroyo',
            'patiño',
            'patron',
            'pava',
            'paz',
            'pedraza',
            'pedroza',
            'pelaez',
            'pelayo',
            'peña',
            'penagos',
            'peñaloza',
            'peñaranda',
            'peñuela',
            'peralta',
            'perdomo',
            'perea',
            'pereira',
            'pérez',
            'perlaza',
            'pertuz',
            'pescador',
            'petro',
            'piamba',
            'pico',
            'piedrahita',
            'pineda',
            'piñeros',
            'pinilla',
            'pino',
            'pinto',
            'pinzon',
            'pita',
            'plata',
            'plaza',
            'plazas',
            'polanco',
            'polania',
            'polo',
            'ponce',
            'ponguta',
            'ponte',
            'porras',
            'portilla',
            'portillo',
            'posada',
            'posso',
            'possu',
            'poveda',
            'prada',
            'prado',
            'preciado',
            'prieto',
            'puello',
            'puentes',
            'puerta',
            'puerto',
            'pulgarin',
            'pulido',
            'quesada',
            'quevedo',
            'quiceno',
            'quijano',
            'quiñones',
            'quiñonez',
            'quintana',
            'quintero',
            'quiroga',
            'quiroz',
            'rada',
            'ramirez',
            'ramos',
            'rangel',
            'rayo',
            'realpe',
            'recalde',
            'reina',
            'rendon',
            'rengifo',
            'restrepo',
            'rey',
            'reyes',
            'riaño',
            'ricardo',
            'ricaurte',
            'rico',
            'rincon',
            'rios',
            'rivas',
            'rivera',
            'riveros',
            'roa',
            'robayo',
            'robles',
            'rocha',
            'rodas',
            'rodríguez',
            'rojas',
            'roldan',
            'roman',
            'romero',
            'romo',
            'roncancio',
            'rondon',
            'rosa',
            'rosales',
            'rosas',
            'rosero',
            'rozo',
            'ruales',
            'ruano',
            'rubiano',
            'rubio',
            'rucinque',
            'rueda',
            'rugeles',
            'ruiz',
            'saavedra',
            'sabogal',
            'saenz',
            'saez',
            'salamanca',
            'salas',
            'salazar',
            'salcedo',
            'saldaña',
            'saldarriaga',
            'salgado',
            'salinas',
            'samboni',
            'sanabria',
            'sánchez',
            'sandoval',
            'santa',
            'santacruz',
            'santamaría',
            'santana',
            'santander',
            'santiago',
            'santos',
            'santoyo',
            'sarasty',
            'sarmiento',
            'sarria',
            'segura',
            'sepulveda',
            'sequeda',
            'serna',
            'serrano',
            'sierra',
            'silva',
            'sinisterra',
            'socha',
            'solano',
            'solarte',
            'soler',
            'solis',
            'sora',
            'sosa',
            'sotelo',
            'soto',
            'suarez',
            'suaza',
            'tabares',
            'taborda',
            'tafur',
            'tamayo',
            'tapias',
            'tarazona',
            'tarquino',
            'tavera',
            'tejada',
            'tellez',
            'tenorio',
            'tirado',
            'tobar',
            'tobon',
            'toledo',
            'toloza',
            'torijano',
            'toro',
            'torrado',
            'torre',
            'torres',
            'tovar',
            'trejos',
            'triana',
            'triviño',
            'trochez',
            'trujillo',
            'turizo',
            'tuta',
            'ulloa',
            'umaña',
            'urango',
            'urbano',
            'urbina',
            'uribe',
            'urrea',
            'urrego',
            'urueña',
            'useche',
            'usme',
            'usuga',
            'vaca',
            'valbuena',
            'valderrama',
            'valdes',
            'valdivieso',
            'valencia',
            'valenzuela',
            'valero',
            'valle',
            'vallejo',
            'vanegas',
            'varela',
            'vargas',
            'varon',
            'vasco',
            'vasquez',
            'vega',
            'vela',
            'velandia',
            'velasco',
            'velasquez',
            'velez',
            'veloza',
            'vera',
            'vergara',
            'vesga',
            'victoria',
            'vidal',
            'villa',
            'villabona',
            'villada',
            'villadiego',
            'villalba',
            'villalobos',
            'villamarin',
            'villamil',
            'villamizar',
            'villanueva',
            'villarreal',
            'villate',
            'villegas',
            'viloria',
            'vinasco',
            'vivas',
            'viveros',
            'vries',
            'wilches',
            'yepes',
            'yepez',
            'zabala',
            'zambrano',
            'zamora',
            'zapata',
            'zarate',
            'zuleta',
            'zuluaga',
            'zúñiga',
        ];

        // Connectors
        $terms['C'] = [
            'cdte',
            'coronel',
            'ct',
            'dc',
            'de',
            'del',
            'di',
            'doctor',
            'el',
            'fray',
            'general',
            'la',
            'las',
            'los',
            'mayor',
            'my',
            'san',
            'santa',
            'santísima',
            'señor',
            'señora',
            'señorita',
            'sr',
            'sra',
            'srta',
            'te',
            'teniente',
            'vda',
            'viuda',
            'y',
        ];

        foreach ($terms as $key => $list) {
            foreach ($list as $term) {
                $k = $key;
                $gender = null;
                if ($key === 'M' || $key === 'F') {
                    $k = 'N';
                    $gender = $key;
                }
                $cleanTerm = $this->partCleaner->clean($term);
                // Since the relation [term, key] is unique
                if (!SplitTerm::where('term', $cleanTerm)->where('type', $k)->exists()) {
                    $t = new SplitTerm();
                    $t->term = $cleanTerm;
                    $t->type = $k;
                    $t->gender = $gender;
                    $t->canonical = mb_strtolower($term, 'UTF-8') !== $cleanTerm ? mb_strtolower($term, 'UTF-8') : '';
                    $t->save();
                }
            }
        }
    }
    public function loadRules()
    {

        $rules = [
            // Nombres con un apellido
            'NL' => '13',
            'NNL' => '123',
            'NNNL' => '1223',
            'NCNL' => '1223',
            'NCNNL' => '12223',
            'NCNCNL' => '122223',
            // Nombres con un apellido y conector
            'NCL' => '133',
            'NNCL' => '1233',
            'NNNCL' => '12233',
            'NCNCL' => '12233',
            'NCNNCL' => '122233',
            'NCNCNCL' => '1222233',
            // Nombres con dos apellidos
            'NLL' => '134',
            'NNLL' => '1234',
            'NNNLL' => '12234',
            'NCNLL' => '12234',
            'NCNNLL' => '122234',
            'NCNCNLL' => '1222234',
            // Nombres con dos apellidos y un conector
            'NLCL' => '1344',
            'NNLCL' => '12344',
            'NNNLCL' => '122344',
            'NCNLCL' => '122344',
            'NCNNLCL' => '1222344',
            'NCNCNLCL' => '12222344',
            // Nombres con dos apellidos y dos conectores
            'NCLCL' => '13344',
            'NNCLCL' => '123344',
            'NNNCLCL' => '1223344',
            'NCNCLCL' => '1223344',
            'NCNNCLCL' => '12223344',
            'NCNCNCLCL' => '122223344',
            // Nombres con dos apellidos y conector final
            'NCLL' => '1334',
            'NNCLL' => '12334',
            'NNNCLL' => '122334',
            'NCNCLL' => '122334',
            'NCNNCLL' => '1222334',
            'NCNCNCLL' => '12222334',

            'NNCNLL' => '122234',
            'NLLCL' => '13444',
            'NLLL' => '1344',
            'NNLLL' => '12344',
            'NNNLLL' => '122344',
            'NNLCLL' => '123444',

            'LCLN' => '3441',
            'LCLNN' => '34412',
            'LN' => '31',
            'LNCN' => '3122',
            'LNN' => '312',
            'LLN' => '341',
            'LLNN' => '3412',
            'LNL' => '123',
        ];

        foreach ($rules as $rule => $distribution) {
            if (!SplitRule::where('rule', $rule)->exists() && strlen($rule) === strlen($distribution)) {
                $r = new SplitRule();
                $r->rule = $rule;
                $r->distribution = $distribution;
                $r->save();
            }
        }
    }
    public function loadSustitutions()
    {

        $sustitutions = [
            'LL' => 'NL',
            'LLIL' => 'NNLL',
            'LXNX' => 'LLNN',
            'NCLCX' => 'NCLCL',
            'NCLXL' => 'NCLCL',
            'NCNLCX' => 'NCNLCL',
            'NCNLXL' => 'NCNLCL',
            'NCNX' => 'NCNL',
            'NCNXCL' => 'NCNLCL',
            'NCX' => 'NCL',
            'NCXCL' => 'NCNCL',
            'NCXL' => 'NCNL',
            'NCXLCL' => 'NCNLCL',
            'NCXLX' => 'NCNLL',
            'NCXX' => 'NCNL',
            'NIL' => 'NNL',
            'NILI' => 'NNLL',
            'NILL' => 'NNLL',
            'NLI' => 'NLL',
            'NLN' => 'NLL',
            'NLX' => 'NLL',
            'NLXL' => 'NLCL',
            'NN' => 'NL',
            'NNCNXX' => 'NNCNLL',
            'NNCXCX' => 'NNCLCL',
            'NNLC' => 'NNLL',
            'NNLI' => 'NNLL',
            'NNLN' => 'NNLL',
            'NNLX' => 'NNLL',
            'NNX' => 'NNL',
            'NNXL' => 'NNLL',
            'NNXX' => 'NNLL',
            'NX' => 'NL',
            'NXCX' => 'NNCL',
            'NXL' => 'NLL',
            'NXLL' => 'NNLL',
            'NXLN' => 'NNLL',
            'NXLX' => 'NNLL',
            'NXNLCL' => 'NCNLCL',
            'NXX' => 'NLL',
            'NXXL' => 'NNLL',
            'NXXX' => 'NNLL',
            'XCL' => 'NCL',
            'XCLCL' => 'NCLCL',
            'XCNL' => 'NCNL',
            'XCNLCL' => 'NCNLCL',
            'XCNX' => 'NCNL',
            'XCNXX' => 'NCNLL',
            'XCX' => 'NCL',
            'XCXLCL' => 'NCNLCL',
            'XCXLL' => 'NCNLL',
            'XCXXX' => 'NCNLL',
            'XIL' => 'NNL',
            'XL' => 'NL',
            'XLCL' => 'NLCL',
            'XLL' => 'NLL',
            'XLX' => 'NLL',
            'XNCL' => 'NNCL',
            'XNCX' => 'NNCL',
            'XNL' => 'NNL',
            'XNLI' => 'NNLL',
            'XNLL' => 'NNLL',
            'XNX' => 'NNL',
            'XNXL' => 'NNLL',
            'XNXX' => 'NNLL',
            'XX' => 'NL',
            'XXCL' => 'NLCL',
            'XXL' => 'NNL',
            'XXLL' => 'NNLL',
            'XXLX' => 'NNLL',
            'XXX' => 'NNL',
            'XXXL' => 'NNLL',
            'XXXX' => 'NNLL'
        ];

        foreach ($sustitutions as $origin => $rule) {
            if (!SplitSustitution::where('origin', $origin)->exists() && SplitRule::where('rule', $rule)->exists() && strlen($rule) === strlen($origin)) {
                $r = new SplitSustitution();
                $r->origin = $origin;
                $r->rule = $rule;
                $r->save();
            }
        }
    }
    public function loadLessons()
    {
        $lessons = [
            'LCLNX' => 'N',
            'LCLXN' => 'N',
            'LLNX' => 'N',
            'LLXN' => 'N',
            'LNCX' => 'N',
            'LXNN' => 'L',
            'NCNLCX' => 'L',
            'NCNLX' => 'L',
            'NCNXCL' => 'L',
            'NCNXL' => 'L',
            'NCXLCL' => 'N',
            'NCXLL' => 'N',
            'NLX' => 'L',
            'NNLCX' => 'L',
            'NNLX' => 'L',
            'NNX' => 'L',
            'NNXCL' => 'L',
            'NNXL' => 'L',
            'NXLCL' => 'N',
            'NXLL' => 'N',
            'XCNLCL' => 'N',
            'XCNLL' => 'N',
            'XLL' => 'N',
            'XLNN' => 'L',
            'XNL' => 'N',
            'XNLCL' => 'N',
            'XNLL' => 'N',
        ];
        foreach ($lessons as $rule => $type) {
            if (!SplitLesson::where('rule', $rule)->exists()) {
                $l = new SplitLesson();
                $l->rule = $rule;
                $l->type = $type;
                $l->save();
            }
        }
    }
    public function loadSamples()
    {
    }
}
