<?php

use Illuminate\Support\Facades\Route;
use Micros\Splitname\SplitName;

Route::get('contact', function () {
    $splitter = new SplitName();
    $splitter->init();
    $tests = [
        'Luis Pedro Gomez Pintón',
        'Prueba  de: uno, dos. tres; cuatro: cinco-  asignación   de nombres 125 gatos , . 
        con espacios incluidos á é íóúñÑ
    
    
        A',
        'Leonardo Forero Sandoval',
        'GERMÁN MEDINA PÉREZ',
        'Díaz Duran, Adriana',
        'Leonardo Forero Sandoval,... y Juán José López',
        'Alfonso Gómez Santiago',
        'JUAN DAVID GÓMEZ P.',
        'Veneranda Arboleda viuda de Álvarez',
        'José María Cordova',
        'María José Forero Leal',
        'Martín Miguel de Güemes.',
        'María Remedios del Valle.',
        'José de San Martín',
        'José Francisco de San Martín y Matorras.',
        'Manuel José Joaquín del Corazón de Jesús Belgrano.',
        'Cornelio Judas Tadeo de Saavedra y Rodríguez.',
        'Bernardino de la Trinidad González de Rivadavia y Rodríguez de Rivadavia.',
        'Martín Miguel Juan de Mata Güemes Montero de Goyechea y la Corte.',
        'Francisco José de Paula Santander Omaña',
        'Simón de la Santísima Trinidad Bolívar Ponte',
        'delcy gomez viuda de rodriguez',
        'Carmen Herrera García Vda. de López',
        'maria de la luz arbelaez',
        'maria de la paz jaramillo',
        'Nadia Blel Scaff',
        'Carlos Andrés Trujillo',
        'Marcos Daniel Pineda',
        'Efraín José Cepeda',
        'Liliana Esther Bitar',
        'Óscar Barreto Quiroga',
        'Diela Liliana Benavides',
        'Óscar Mauricio Giraldo',
        'Nicolás Albeiro Echeverry',
        'Juan Samy Mereg Marún',
        'Germán Alcides Blanco',
        'Juan Carlos García Gómez',
        'José Alfredo Marín',
        'Miguel Ángel Barreto',
        'Soledad Tamayo',
        'Lidio Arturo García',
        'Juan Pablo Gallo Maya',
        'Karina Espinosa Oliver',
        'Alejandro Carlos Chacón',
        'Fabio Raúl Amín',
        'Miguel Ángel Pinto',
        'Claudia María Pérez',
        'Alejandro Alberto Vega',
        'Juan Diego Echavarría',
        'Jaime Enrique Durán',
        'John Jairo Roldán',
        'Mauricio Gómez Amín',
        'Mario Alberto Castaño',
        'Laura Ester Fortich Sánchez',
        'Jonathan Ferney Pulido Hernández',
        'Humberto de la Calle',
        'Ariel Ávila',
        'Angélica Lozano',
        'Inti Asprilla',
        'Jairo Alberto Castellanos',
        'Ana Carolina Espitia',
        'Guido Echeverry Piedrahíta',
        'Andrea Padilla Villarraga',
        'Edwing Fabián Díaz Plata',
        'Gustavo Adolfo Moreno Hurtado',
        'Sor Berenice Bedoya Pérez',
        'Iván Name',
        'Miguel Uribe Turbay',
        'María Fernanda Cabal',
        'Josué Alirio Barrera',
        'Andrés Felipe Guerra Hoyos',
        'Esteban Quintero Cardona',
        'Paola Holguín Moreno',
        'Paloma Susana Valencia Laserna',
        'Enrique Cabrales Baquero',
        'Carlos Manuel Meisel Vergara',
        'Ciro Alejandro Ramírez',
        'José Vicente Carreño Castro',
        'Honorio Miguel Henríquez Pinedo',
        'Yenny Esperanza Rozo Zambrano',
        'José Maria Chema',
        'Maria José Chema',
        'Julián Gallo Cubillos',
        'Ómar de Jesús Restrepo Correa',
        'Pablo Catatumbo Torres Victoria',
        'Imelda Daza Cotes',
        'Maria del Pilar Torres',
        'Sandra Ramírez Lobo Silva',
        'Giovanna de la la de María de la la Torres',
        'Juan David Mesa de la Peña',
        'Maria del Mar Sanchez de la Cuarta',
        'de la Torre Sanchez, Maria del Mar',
        'Armando Bernardo Complejo Zuluaga',
        ' Juan José Antonio Castelli',
        ' Guillermo Brown',
        'Juan Bautista Alberdi Aráoz',
        ' Juan Manuel José Domingo Ortiz de Rozas y López de Osornio',
        "Bernardo O'Higgins Riquelme",
        "María Isabel Riquelme y Meza",
        "Juan Albano Pereira Márquez",
        "Bartolina de la Cruz y Bahamonde.",
        "Manuel Montt Torres",
        "Pedro de Alcántara Francisco Antonio Juan Carlos Javier de Paula Miguel Rafael Joaquín José Gonzaga Pascual Cipriano Serafín",
        "Andrés Mendigure Túpac Amaru",
        "Mariano José de Arce Bedrigal",
        "José Manuel Robles Arnao y García",
        "Juan Francisco de Vidal La Hoz",
        "Túpac Amaru II",
        "José María Pérez y Armendáriz",
        "Manuela de la Santa Cruz y Espejo",
        "Manuel de Larrea y Jijón",
        "Francisco Javier de Ascázubi",
        "Juan de Salinas y Zenitagoya",
        "Francisco Javier de Montoya y González de Castro",
        "María Rita Duque de Estrada y Salazar",
        "Antonio María Sinforoso Arboleda y Arrachea ",
        "Fray Ignacio Mariño y Torres",
        "TE Edwin de Jesús Francisco Gómez Ovalle de Medina y López",
        "Carlos Juan Fitz-James-Stuart y Martínez de Irujo",
        "Matilde de Solís-Beaumont y Martínez de Campos",
        "Maya Ruiz-Picasso, ",
        "Ambrosio Bernardo O'Higgins y O'Higgins",

    ];

    foreach ($tests as $test) {
        if ($test) {
            $name = $splitter->split($test);
            echo str_repeat('*', 40) . PHP_EOL;
            echo $test . PHP_EOL;
            dump($name);
        }
    }

    $splitter->process();
    return 'Hello from the contact form package';
});
